[package]
name = "hello-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.18.18"
solana-frozen-abi = "=1.18.18"
solana-frozen-abi-macro = "=1.18.18"
solana-sdk-macro = "=1.18.18"

[lib]
crate-type = ["cdylib"]